import type { Plan } from "./types";

export const DEFAULT_PLANS: Plan[] = [
  {
    id: "basico",
    nome: "Básico",
    perfil_cliente: "Carteira pequena (1 a 3 médicos)",
    descricao: "Ideal para secretárias que gerenciam até 3 médicos e faturamento inicial.",
    cnpjs_inclusos: 3,
    notas_mes_limite: 500,
    preco_mensal: 297.0,
    custo_api_estimado: 153.9,
    lucro_estimado: 143.1,
    margem_percentual: 48,
    destaque: false,
    ordem: 1,
    checkout_url: "https://invoice.infinitepay.io/plans/respiru/HwvkqORyco",
    recursos: [
      "Até 3 CNPJs cadastrados",
      "500 notas fiscais por mês",
      "Importação de XML de notas anteriores",
      "Download de DANFSe (PDF) e XML",
      "Suporte por e-mail e WhatsApp",
    ],
  },
  {
    id: "profissional",
    nome: "Profissional",
    perfil_cliente: "Carteira cheia (Volume alvo)",
    descricao: "O plano mais popular para secretárias com alta demanda de consultas e emissões diárias.",
    cnpjs_inclusos: 5,
    notas_mes_limite: 1500,
    preco_mensal: 547.0,
    custo_api_estimado: 329.7,
    lucro_estimado: 217.3,
    margem_percentual: 39,
    destaque: true,
    ordem: 2,
    checkout_url: "https://invoice.infinitepay.io/plans/respiru/aZnWNexG3Y",
    recursos: [
      "Até 5 CNPJs cadastrados",
      "1.500 notas fiscais por mês",
      "Emissão com 1 clique e data personalizada",
      "Central de NFS-e e cancelamento integrado",
      "Alertas automáticos de vencimento e cotas",
      "Suporte prioritário via WhatsApp",
    ],
  },
  {
    id: "agencia",
    nome: "Agência",
    perfil_cliente: "Expansão / Múltiplas assistentes",
    descricao: "Para escritórios de assessoria médica, clínicas em rede e múltiplos assistentes.",
    cnpjs_inclusos: 15,
    notas_mes_limite: 4000,
    preco_mensal: 1197.0,
    custo_api_estimado: 740.0,
    lucro_estimado: 457.0,
    margem_percentual: 38,
    destaque: false,
    ordem: 3,
    checkout_url: "https://invoice.infinitepay.io/plans/respiru/1JNDry40A2",
    recursos: [
      "Até 15 CNPJs cadastrados",
      "4.000 notas fiscais por mês",
      "Múltiplos emissores e clínicas médicas",
      "Relatórios consolidados para contabilidade",
      "Gestão avançada de faturas e comprovantes",
      "Gerente de conta exclusivo",
    ],
  },
];
